CAMERA_INDEX = 0

CAPTURE_FPS = 30
PROCESS_EVERY_N_FRAMES = 1

EAR_BLINK_THRESHOLD = 0.24
EAR_CONSEC_FRAMES = 3

LOW_BLINK_RATE = 10
CONTINUOUS_STARE_SEC = 20
MAX_SCREEN_TIME_MIN = 40
BREAK_DURATION_SEC = 20

COOLDOWN_BLINK = 120
COOLDOWN_STARE = 60
COOLDOWN_SCREEN_TIME = 300

SAVE_VIDEO = False
CLOUD_PROCESSING = False